# Generated by Django 5.2.5 on 2025-09-08 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('numero_cuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procedencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_liquidacion', models.CharField(max_length=50)),
                ('numero_despacho', models.CharField(max_length=50)),
                ('clase', models.CharField(choices=[('importacion', 'Importación'), ('exportacion', 'Exportación')], max_length=20)),
                ('numero_factura_comercial', models.CharField(max_length=50)),
                ('partida_arancelaria', models.CharField(max_length=50)),
                ('ad_valorem', models.CharField(max_length=50)),
                ('valor_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_valor_imponible', models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('GUARANIES', 'Guaraníes')], max_length=10)),
                ('equivalente_gs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_cambio', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.liquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('concepto', models.TextField(blank=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.banco')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='clientes.cliente')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('procedencia', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='liquidaciones.procedencia')),
            ],
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liquidaciones.proveedor'),
        ),
    ]
