# Generated by Django 5.2.5 on 2025-09-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pago",
            name="cliente",
        ),
        migrations.AddField(
            model_name="pago",
            name="numero_despacho",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pago",
            name="banco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="liquidaciones.banco"
            ),
        ),
    ]
