# Generated by Django 5.2.5 on 2025-09-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0002_remove_pago_cliente_pago_numero_despacho_and_more"),
    ]

    operations = [
        # First remove the old field
        migrations.RemoveField(
            model_name="pago",
            name="numero_despacho",
        ),
        # Then add the new field - since no data exists, we can make it required
        migrations.AddField(
            model_name="pago",
            name="liquidacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="liquidaciones.liquidacion"
            ),
        ),
        # Update the model options
        migrations.AlterModelOptions(
            name="pago",
            options={"ordering": ["-fecha"]},
        ),
    ]