# Generated by Django 5.2.5 on 2025-09-09 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0003_pago_liquidacion_remove_pago_numero_despacho"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanillaGastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("numero_planilla", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Planilla de Gastos",
                "verbose_name_plural": "Planillas de Gastos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="planilla_gastos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="liquidaciones.planillagastos",
            ),
        ),
        migrations.CreateModel(
            name="PlanillaGastosItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "planilla_gastos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="liquidaciones.planillagastos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Planilla de Gastos",
                "verbose_name_plural": "Items de Planilla de Gastos",
            },
        ),
    ]
