# Generated by Django 4.2.29 on 2026-04-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0004_planillagastos_liquidacion_planilla_gastos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="orden_de_compra",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="proforma",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
