# Generated by Django 4.2.29 on 2026-04-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0005_liquidacion_orden_de_compra_liquidacion_proforma"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacionitem",
            name="item",
            field=models.CharField(max_length=255),
        ),
    ]
