# Generated by Django 4.2.29 on 2026-04-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0006_liquidacionitem_item_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="factura",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="flete",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="seguro",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
