# Generated by Django 4.2.29 on 2026-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0007_liquidacion_factura_flete_seguro"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacion",
            name="detalle_de_contenido",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
