# Generated by Django 4.2.29 on 2026-07-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("liquidaciones", "0008_add_detalle_de_contenido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liquidacion",
            old_name="tipo_cambio",
            new_name="tipo_cambio_despacho",
        ),
        migrations.AddField(
            model_name="liquidacion",
            name="tipo_cambio_factura",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
